export const artists = [
    "coez",
    "rkomi",
    "willie peyote",
    "ernia",
    "carl brave",
    "frah quintale",
    "franco126",
    "lowlow",
    "tredici pietro",
    "rovere",
    "calcutta",
    "ariete",
    "fulminacci",
    "galeffi",
    "legno",
    "mecna",
    "tananai",
    "psicologi",
    "canova",
    "morbici",
    "bnk44",
    "ex-otago",
    "fast animals and slow kids",
    "giorgio poi",
    "svegliaginevra",
    "gazzelle",
    "dutch nazari",
    "laila al habash",
    "labadessa",
    "caterina",
    "la rappresentante di lista",
    "coma_cose",
    "peter white",
    "venerus",
]